name: Backend CI

on:
  push:
    branches:
      # Workflow triggered when code is pushed to these branches
      - main
      - dev

  pull_request:
    branches:
      # Workflow triggered when a PR targets these branches
      - main
      - dev

jobs:
  run_back_ci:
    # Define the operating system for the CI runner
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:18
        env:
          POSTGRES_USER: lapince_user
          POSTGRES_PASSWORD: lapince_password
          POSTGRES_DB: lapince_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      NODE_ENV: test
      PORT: 3000
      DATABASE_URL: postgresql://lapince_user:lapince_password@localhost:5432/lapince_db
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout code
        # Clones the repository so the workflow can access the code
        uses: actions/checkout@v5

      - name: Setup Node.js
        # Sets up the Node.js environment for the CI pipeline
        uses: actions/setup-node@v5
        with:
          node-version: 24
          # Enables dependency caching to speed up installs
          cache: npm

      - name: Install dependencies
        # Installs project dependencies using clean install / npm install installs dependencies and may update the package-lock.json file.
        run: npm i
      
      - name: Generate Prisma client
        run: npx prisma generate
      
      - name: Run migrations
        run: npx prisma migrate deploy

      - name: Validate project
        # Runs project checks (linting, type-checking, etc.)
        run: npm run check

      - name: Setup test environment
        run: cp .env.test.example .env.test

      - name: Unit tests project
      #   # Run units tests
        run: npm run test:unit

      - name: Integration tests
      #   # Run integration tests
        run: npm run test:integration